[project]
name = "OHW-hab"
version = "0.1.0"
description = "Add a short description here"
authors = ["Adelle Pitsas <apitsas@gmri.org>"]
channels = ["conda-forge"]
platforms = ["osx-arm64"]

[tasks]

[dependencies]
pip = ">=24.2,<25"
xarray = ">=2024.7.0,<2024.8"
streamlit = ">=1.38.0,<1.39"
erddapy = ">=2.2.0,<2.3"
altair = "<5"
dask = ">=2023.10.1,<2023.11"
earthaccess = ">=0.10.0,<0.11"
matplotlib = ">=3.9.2,<3.10"
cmocean = ">=4.0.3,<4.1"
coiled = ">=1.45.0,<1.46"
netcdf4 = ">=1.7.1,<1.8"
h5netcdf = ">=1.3.0,<1.4"
"backports.tempfile" = ">=1.0,<2"
numpy = ">=1.26.4,<1.27"
geopandas = ">=1.0.1,<1.1"
pandas = ">=2.2.2,<2.3"
