[project]
name = "OHW-hab"
version = "0.1.0"
description = "Add a short description here"
authors = ["Adelle Pitsas <apitsas@gmri.org>"]
channels = ["conda-forge"]
platforms = ["osx-arm64"]

[tasks]

[dependencies]
pip = ">=24.2,<25"
pandas = ">=2.2.2,<2.3"
xarray = ">=2024.7.0,<2024.8"
streamlit = ">=1.9.0,<1.10"
erddapy = ">=2.2.0,<2.3"
altair = "<5"
dask = ">=2023.10.1,<2023.11"
